"""Request and response schemas for recommendation endpoints."""

from typing import List

from pydantic import BaseModel, Field


class Question(BaseModel):
    """Individual interview question with metadata.

    Attributes:
        id (int): Unique identifier for the question
        text (str): The interview question text
        category (str): Category of the question
    """

    id: int = Field(..., description="Unique identifier for the question")
    text: str = Field(..., description="The interview question text")
    category: str = Field(..., description="Category of the question")


class RecommendationRequest(BaseModel):
    """Request schema for interview recommendations.

    Attributes:
        job_title (str): The job position to generate interview questions for
        model (str): AI model to use - either 'gemini' or 'groq' (default: 'gemini')
    """

    job_title: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Job title or position for which to generate interview questions",
        example="Senior Software Engineer",
    )
    model: str = Field(
        default="gemini",
        description="AI model to use for generating questions",
        examples=["gemini", "groq"],
    )

    class Config:
        """Pydantic config."""

        json_schema_extra = {
            "example": {"job_title": "Product Manager", "model": "gemini"},
        }


class RecommendationResponse(BaseModel):
    """Response schema for interview recommendations.

    Attributes:
        questions (List[Question]): List of generated interview questions with metadata
    """

    questions: List[Question] = Field(
        ...,
        description="List of interview questions generated by the AI with metadata",
        example=[
            {
                "id": 1,
                "text": "What's your experience with agile methodologies?",
                "category": "methodology",
            },
            {
                "id": 2,
                "text": "How do you prioritize tasks in a fast-paced environment?",
                "category": "time-management",
            },
            {
                "id": 3,
                "text": "Describe your approach to cross-team collaboration.",
                "category": "teamwork",
            },
        ],
    )

    class Config:
        """Pydantic config."""

        json_schema_extra = {
            "example": {
                "questions": [
                    {
                        "id": 1,
                        "text": "What experience do you have with this technology?",
                        "category": "technical-skills",
                    },
                    {
                        "id": 2,
                        "text": "How do you approach problem-solving?",
                        "category": "problem-solving",
                    },
                    {
                        "id": 3,
                        "text": "Tell us about a challenging project you led.",
                        "category": "leadership",
                    },
                ]
            },
        }