"""Request and response schemas for recommendation endpoints."""

from typing import List

from pydantic import BaseModel, Field


class RecommendationRequest(BaseModel):
    """Request schema for interview recommendations.

    Attributes:
        job_title (str): The job position to generate interview questions for
    """

    job_title: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Job title or position for which to generate interview questions",
        example="Senior Software Engineer",
    )

    class Config:
        """Pydantic config."""

        json_schema_extra = {
            "example": {"job_title": "Product Manager"},
        }


class RecommendationResponse(BaseModel):
    """Response schema for interview recommendations.

    Attributes:
        questions (List[str]): List of generated interview questions
    """

    questions: List[str] = Field(
        ...,
        description="List of interview questions generated by the AI",
        example=[
            "What's your experience with agile methodologies?",
            "How do you prioritize tasks in a fast-paced environment?",
            "Describe your approach to cross-team collaboration.",
        ],
    )

    class Config:
        """Pydantic config."""

        json_schema_extra = {
            "example": {
                "questions": [
                    "What experience do you have with this technology?",
                    "How do you approach problem-solving?",
                    "Tell us about a challenging project you led.",
                ]
            },
        }